USE Menu;
GO

SELECT RecipeID,
	SYS_CHANGE_OPERATION AS ChangeOperation,
	CHANGE_TRACKING_IS_COLUMN_IN_MASK
	(COLUMNPROPERTY
		(OBJECT_ID('Recipe'), 'RecipeName', 'ColumnId'),
	SYS_CHANGE_COLUMNS) AS NameChange,
	CHANGE_TRACKING_IS_COLUMN_IN_MASK
	(COLUMNPROPERTY
		(OBJECT_ID('Recipe'), 'RecipeDescription', 'ColumnId'),
	SYS_CHANGE_COLUMNS) AS DescChange,
	CHANGE_TRACKING_IS_COLUMN_IN_MASK
	(COLUMNPROPERTY
		(OBJECT_ID('Recipe'), 'IsActive', 'ColumnId'),
	SYS_CHANGE_COLUMNS) AS IsActiveChange,
	CHANGE_TRACKING_IS_COLUMN_IN_MASK
	(COLUMNPROPERTY
		(OBJECT_ID('Recipe'), 'DateCreated', 'ColumnId'),
	SYS_CHANGE_COLUMNS) AS CreateChange,
	CHANGE_TRACKING_IS_COLUMN_IN_MASK
	(COLUMNPROPERTY
		(OBJECT_ID('Recipe'), 'DateModified', 'ColumnId'),
	SYS_CHANGE_COLUMNS) AS ModifiedChange,
	SYS_CHANGE_CONTEXT
FROM CHANGETABLE
(CHANGES dbo.Recipe,0) as ChngTbl
ORDER BY SYS_CHANGE_VERSION