USE Menu;
GO

ALTER DATABASE Menu
ADD FILEGROUP RecipeHistory2018;

ALTER DATABASE Menu
ADD FILEGROUP RecipeHistory2019Q1;

ALTER DATABASE Menu
ADD FILEGROUP RecipeHistory2019Q2;

ALTER DATABASE Menu
ADD FILEGROUP RecipeHistory2019Q3;